title: Diana Chacon
#logo: /assets/img/headshot_circle.png
description: >
  UC Berkeley MS Data Science graduate with 10+ years of experience in Environmental Remediation Consulting, Geographic Information Systems, and Data Analysis, with a proven track record of implementing data solutions for enterprise customers and government regulators. 
  <br>
  <br>
  <a href="www.linkedin.com/in/diana-chacon/">View My Linkedin Profile</a>
show_downloads: true
theme: jekyll-theme-minimal
