title: Diana Chacon
#logo: /assets/img/headshot_circle.png
description: >
  <br>
  With over 15 years of experience as an Environmental Scientist, specializing in environmental analysis, data management, and geospatial data science, I have a proven track record of leveraging data-driven insights to solve complex environmental challenges. My expertise in Geographic Information Systems (GIS) and data analysis has been instrumental in managing and interpreting large datasets, enabling me to deliver actionable strategies that drive impactful decisions.

Building on this foundation, I earned a Masters degree in Data Science from the University of California, Berkeley, where I honed my skills in advanced statistical analysis, machine learning, and data visualization. This portfolio showcases projects that highlight my ability to extract meaningful insights from complex data sets and my commitment to applying data science techniques across various industries.
    <br>
    <br>
    <a href="www.linkedin.com/in/diana-chacon/">View My Linkedin Profile</a>
show_downloads: true
theme: jekyll-theme-minimal
