title: Diana Chacon
#logo: /assets/img/headshot_circle.png
description: >
  <br>
  As a seasoned Environmental Scientist with over 15 years of experience in environmental analysis, data management, and geospatial data science, I have consistently focused on leveraging data-driven insights to address complex environmental challenges.
    <br>
    <br>
  Earning my Master&#39;s degree in Data Science from the University of California, Berkeley, has further refined my skills in advanced statistical analysis, machine learning, and data visualization. This academic achievement, combined with my extensive professional experience, uniquely positions me to bridge the gap between environmental science and data science, delivering insights that drive impactful decisions.
    <br>
    <br>
  Throughout my career, I have been dedicated to transforming environmental data into actionable strategies. My expertise in Geographic Information Systems (GIS) and data analysis has been crucial in managing and interpreting large datasets, fueling my passion for a deeper focus on data science. I am now eager to apply these skills to broader data science challenges, where I can explore innovative methods to uncover patterns, predict outcomes, and optimize processes across various industries.
    <br>
    <br>
  This portfolio reflects my transition from environmental analysis to data science, featuring projects that demonstrate my ability to extract meaningful insights from complex data sets. It also underscores my commitment to continuous learning and growth in this dynamic field. 
    <br>
    <br>
    <a href="www.linkedin.com/in/diana-chacon/">View My Linkedin Profile</a>
show_downloads: true
theme: jekyll-theme-minimal
